  ---
    - hosts: UbuntuS
      become: True
      vars:
         username: "qepbelen"
         motd: "Ansible Managed node by ebelen"
      roles:
        - python
        - java
        - ChangeMOTD
        - CreateUser
